apiVersion: apps/v1
kind: Deployment
metadata:
  name: newaksdemoapi-deployment
  labels:
    app: NewAKSDemoAPI
spec:
  replicas: 1
  selector:
    matchLabels:
      app: NewAKSDemoAPI  
  template:
    metadata:
      labels:
        app: NewAKSDemoAPI
    spec:
      containers:
      - name:  newaksdemoapi
        image: newaksdemocr.azurecr.io/newaksdemocrrepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name:  webapisvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: newaksdemoapisvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app:  NewAKSDemoAPI
